### ISSUE TITLE
SSL expiration checker

### ISSUE THREAD

**Issue by ntalekt** [ntalekt/homeassistant#19]
Need a sensor that will check the expiration date of SSL cert and send a notification if below threshold.

**Comment by ntalekt** [comment]
`ssl-cert-check -b -c /home/homeassistant/.homeassistant/cert.pem  | awk '{ print $NF }'`

**Comment by ntalekt** [comment]
```
sensor:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 86400
    command: "ssl-cert-check -b -c /home/homeassistant/.homeassistant/cert.pem | awk '{ print $NF }'"
```
