### ISSUE TITLE
Needs SSL on Front-end

### ISSUE THREAD

**Issue by ntalekt** [ntalekt/homeassistant#3]
https://www.ssls.com/ssl-certificates/comodo-positivessl

```
http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.1.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3
```

**Comment by ntalekt** [comment]
HTTPS and TTS aren't playing nice.
https://github.com/home-assistant/home-assistant/issues/5064

**Comment by ntalekt** [comment]
I noticed my `base_url` was resolving my outside IP and since it's not open I figured it needed to resolve to my LAN. I updated /etc/hosts on my PiHole RPI and rebooted the HA RPI. On the HA instance my `base_url` now resolves to the LAN. I re-enabled the SSL settings and it still doesn't work. 

This is the config I tried:
```
http:
  base_url: ha.example.com:8123
  api_password: !secret ha_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.1.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3
```
