### ISSUE TITLE
Automation - Notification text when new device connects to network

### ISSUE THREAD

**Issue by ntalekt** [ntalekt/homeassistant#9]
- [x] ~~Update `device_tracker.yaml` so NMAP scans the entire /24~~
- [x] Figure out why [Netgear component](https://home-assistant.io/components/device_tracker.netgear/) won't work for my R7800
- [x] Update `known_devices.yaml` with correct names
- [x] Create automation to look for new devices that show up in `known_devices.yaml`

**Comment by ntalekt** [comment]
Example from https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/automation/Speech/new_device.yaml
```
##############################################################################
###  New Device has connected to the network.  let everyone know.
##############################################################################

- alias: "New device connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device

  action:
    - wait_template: >-
        {{ not is_state('media_player.livingroomCC', 'playing') }}
        
    - service: script.speech_engine
      data_template:
        NewDevice: "There has been a new device detected on the network.  Be sure to appropriately catagorize {{trigger.event.data.host_name}} within Circle."
##############################################################################
```
Another example from https://community.home-assistant.io/t/looking-for-this-automation-security-based/19438/3
```
  - alias: Notify If New Devices
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.home_assistant
        data_template:
          message: >
            New device:
            {{trigger.event.data.host_name}}
            ({{trigger.event.data.entity_id}})
          title: New device
```
